apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: delegated-global-leaf-cert
  namespace: default
spec:
  secretName: delegated-global-leaf-tls
  duration: 2160h
  renewBefore: 360h
  commonName: "global-delegated.hshade.io"
  issuerRef:
    group: scep.hshade.io
    kind: ClusterIssuer
    name: delegated-global-scep-issuer