apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: direct-leaf-cert
  namespace: default
spec:
  secretName: direct-leaf-tls
  duration: 2160h
  renewBefore: 360h
  commonName: "direct.hshade.io"
  issuerRef:
    group: scep.hshade.io
    kind: Issuer
    name: direct-scep-issuer
