apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: delegated-leaf-cert
  namespace: default
spec:
  secretName: delegated-leaf-tls
  duration: 2160h
  renewBefore: 360h
  commonName: "test-app1.hshade.io"
  dnsNames:
    - "test-app1.hshade.io"
    - "alt1.hshade.io"
  issuerRef:
    group: scep.hshade.io
    kind: Issuer
    name: delegated-scep-issuer
