apiVersion: v1
kind: Secret
metadata:
  name: scep-challenge-secret
type: Opaque
stringData:
  password: "SecretChallenge"
---
apiVersion: scep.hshade.io/v1alpha1
kind: Issuer
metadata:
  name: delegated-scep-issuer
spec:
  url: http://192.168.1.34/scep/generic
  enrollmentMode: Delegated
  insecureSkipVerify: true
  challengeSecretRef:
    name: scep-challenge-secret
    key: password
  delegatedSignerConfiguration:
    commonName: "ra.hshade.io"
    dnsNames:
      - "ra.hshade.io"
      - "scep-agent.hshade.io"
    subject:
      organizations:
        - "Hades Inc"
      countries:
        - "ID"
      organizationalUnits:
        - "Infrastructure"