apiVersion: v1
kind: Secret
metadata:
  name: cluster-scep-challenge
  namespace: cert-manager
type: Opaque
stringData:
  password: "SecretChallenge"
---
apiVersion: scep.hshade.io/v1alpha1
kind: ClusterIssuer
metadata:
  name: delegated-global-scep-issuer
spec:
  url: http://192.168.1.34/scep/generic
  enrollmentMode: Delegated
  insecureSkipVerify: true
  challengeSecretRef:
    name: cluster-scep-challenge
    key: password
  delegatedSignerConfiguration:
    commonName: "cluster-ra.hshade.io"